FROM node:14.4.0

# Create app directory
WORKDIR /usr/src/app

COPY . .

# WORKDIR /usr/src/app/view

# RUN npm install

# RUN npm run build

# RUN cp -a ./build/* ../server/client

# WORKDIR /usr/src/app

export CHROME_VERSION=81.0.4044.138-1

export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

RUN set -x \
  && apt-get update \
  && apt-get install wget --yes \
  && wget --no-check-certificate https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb \
  && dpkg -i google-chrome-stable_${CHROME_VERSION}_amd64.deb || apt -y -f install \
  && rm google-chrome-stable_${CHROME_VERSION}_amd64.deb \
  && apt autoremove --yes

ENV CHROME_BIN /usr/bin/google-chrome-stable

RUN npm install --loglevel verbose

RUN pwd

RUN echo "teste"

EXPOSE 3001

# RUN npm run custom-key

CMD [ "npm", "start" ]